### ISSUE TITLE
Removing mod that has items in inventory will cause error when browsing items

### ISSUE THREAD

**Issue by sherkas** [zerofall/EZStorage2#40] opened 2016-10-14 02:46 UTC
Im running into this issue while removing trouble mods here and there. I start by of course adding a mod, adding those items into inventory and it works just fine. A mod will cause issues and I remove it.

At this point the ezstorage will not show the items but will spam the console with: 

[20:41:24] [Server thread/INFO] [STDERR]: [com.zerofall.ezstorage.util.ItemGroup
$EnumSortMode:sortInventory:67]: java.lang.NullPointerException
[20:41:29] [Server thread/INFO] [STDERR]: [com.zerofall.ezstorage.util.ItemGroup
$EnumSortMode:sortInventory:67]: java.lang.NullPointerException
[20:41:42] [Server thread/INFO] [STDERR]: [com.zerofall.ezstorage.util.ItemGroup
$EnumSortMode:sortInventory:67]: java.lang.NullPointerException
[20:41:43] [Server thread/INFO] [STDERR]: [com.zerofall.ezstorage.util.ItemGroup
$EnumSortMode:sortInventory:67]: java.lang.NullPointerException
[20:41:45] [Server thread/INFO]: sherkborg lost connection: TextComponent{text='
Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null,
italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null,
 insertion=null}}

And of course any items pulled out will result in wrong items. No items will autocraft either through JEI.

So to fix this I would love to see a command if anything else say... /ezstorage reinventory which would go through the list and re-validate items and maybe pull out those null/emptys or something. Even an item to wrench smack them which recalcs items too would be nice.

Easy to replicate. Vanilla client. Add a storage system. Add a mod with items, place items in inventory system. Remove mod, and then use system.

**Comment by sherkas** [comment] 2016-10-14 02:47
Oh, 1.10.2 and latest ezstorage if that even matters.

**Comment by sblectric** [comment] 2016-10-14 22:33
Duplicate of #33. All you have to do to fix this problem is reload the world. I might add a fancy workaround for this like the one you've suggested, please add it to the suggestions thread.

**Comment by sblectric** [comment] 2016-11-05 17:52
Fixed, finally.

**Closed by sblectric** 2016-11-05 17:52 UTC
Labels: enhancement, low priority
