### ISSUE TITLE
MP server crash 

### ISSUE THREAD

**Issue by nzhook** [zerofall/EZStorage2#36] opened 2016-10-01 05:24 UTC
We have an weird server crash issue with ezStorage. Not entirely sure what the cause is, beyond items that have been stored.

Opening the ezStorage system will work fine (you can take items out), however after closing the interface. Chests, Machines and anything with an inventory will no longer open for the player who opened the core.   Chat, Elevators and Chunk loading continue to work as normal. In addition when that player disconnects the server will crash taking all the other online players with it.

In a recent example the crash report indicated the Wand Of The Lazy Builder from Ender Utilities was the cause, and removing it from storage resolved the issue. However this can not be reproduced and other crash reports have indicated other items from other mods are the cause.  

Here is the server crash report (the one which indicates the lazy buider was the cause):  [crash-2016-09-30_22.24.26-server.txt](https://github.com/zerofall/EZStorage2/files/504091/crash-2016-09-30_22.24.26-server.txt)

I have also uploaded a video which shows the client side symptoms: https://youtu.be/3oGQQlsZ-zo
(note using the elevator indicates the server is still responding)

**Comment by LemADEC** [comment] 2016-10-01 10:16
Looks like server tries to use client side code to sort by localized names.

**Comment by sblectric** [comment] 2016-10-01 15:19
There are 2 different I18n classes that help with translation. Mods should use the common one (net.minecraft.util.text.translation) that works on both server and client like vanilla items do, but for some reason, Ender Utilities uses the client-sided-only one in this case (net.minecraft.client.resources). I can add a workaround for this, but this isn't strictly EZ's fault.

**Comment by sblectric** [comment] 2016-10-01 16:38
@nzhook could you test a build for me and see if the problem is fixed?

**Comment by sblectric** [comment] 2016-10-01 20:59
Well it should be fixed, so a build will go up on Curseforge now. Reopen this issue if it's still there, but theoretically it's fine now.

**Closed by sblectric** 2016-10-01 20:59 UTC
